export const CALCULATOR_ACTIONS = {
  UPDATE_DISPLAY: 'UPDATE_DISPLAY',
  OPERATOR: 'OPERATOR',
  PREVIOUS_VALUE: 'PREVIOUS_VALUE',
  EQUAL: 'EQUAL',
  CLEAR_DISPLAY: 'CLEAR_DISPLAY',
  CLEAR_HISTORY: 'CLEAR_HISTORY',
  CLEAR_ALL: 'CLEAR_ALL',
  DELETE_LAST_NUMBER: 'DELETE_LAST_NUMBER',
  CHANGE_SIGN: 'CHANGE_SIGN',
};

export const THEME_ACTIONS = {
  CHANGE_THEME: 'CHANGE_THEME',
};